[package]
name = "blocking-io-client"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = {path = "lib/gl"}
nalgebra = "0.29.0"
nalgebra-glm = "0.15.0"
c_str_macro = "1.0.3"
imgui = "0.7.0"
imgui-opengl-renderer = "0.11.0"
image = "0.23.14"
tungstenite = "0.15.0"
